export const HEADER_REQUEST = 'HEADER_REQUEST';
export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_FORGOT_PASSWORD_REQUEST = 'USER_FORGOT_PASSWORD_REQUEST';
export const USER_RESET_PASSWORD_REQUEST = 'USER_RESET_PASSWORD_REQUEST';
export const USER_GET_INFORMATION_REQUEST = 'USER_GET_INFORMATION_REQUEST';
export const USER_SEND_COLLECTION_INFOR_REQUEST = 'USER_SEND_COLLECTION_INFOR_REQUEST';

export const QUERY_HANDLE_FILE = 'QUERY_HANDLE_FILE';

export const ADMIN_CREATE_NEW_USER_REQUEST = 'ADMIN_CREATE_NEW_USER_REQUEST';
export const ADMIN_GET_USER_REQUEST = 'ADMIN_GET_USER_REQUEST';
export const ADMIN_HANDLE_STATUS_USER_REQUEST = 'ADMIN_HANDLE_STATUS_USER_REQUEST';
export const ADMIN_GET_DETAIL_USER_REQUEST = 'ADMIN_GET_DETAIL_USER_REQUEST';

export const CREATE_CLASS_REQUEST = 'CREATE_CLASS_REQUEST';
export const GET_ALL_CLASS_REQUEST = 'GET_ALL_CLASS_REQUEST';

export const DATA_COMPANY_REQUEST = 'DATA_COMPANY_REQUEST';
export const GET_ALL_MAJOR_REQUEST = 'GET_ALL_MAJOR_REQUEST';
export const GET_ALL_PREMISES_REQUEST = 'GET_ALL_PREMISES_REQUEST';

